// Copyright 2023 The Yock Authors. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

package httplib

import (
	"net/http"

	yocki "github.com/ansurfen/yock/interface"
)

func LoadHttp(yocks yocki.YockScheduler) {
	lib := yocks.CreateLib("http")
	lib.SetField(map[string]any{
		// functions
		"ListenAndServe": http.ListenAndServe,
		"TimeoutHandler": http.TimeoutHandler,
		// "ChanCreate":            http.ChanCreate,
		"NotFound":        http.NotFound,
		"StripPrefix":     http.StripPrefix,
		"ParseTime":       http.ParseTime,
		"MaxBytesHandler": http.MaxBytesHandler,
		"Error":           http.Error,
		// "HelloServer":           http.HelloServer,
		"NewFileTransport":  http.NewFileTransport,
		"FileServer":        http.FileServer,
		"ListenAndServeTLS": http.ListenAndServeTLS,
		"HandleFunc":        http.HandleFunc,
		// "FlagServer":            http.FlagServer,
		"Get":             http.Get,
		"SetCookie":       http.SetCookie,
		"NotFoundHandler": http.NotFoundHandler,
		"StatusText":      http.StatusText,
		"MaxBytesReader":  http.MaxBytesReader,
		"NewRequest":      http.NewRequest,
		"RedirectHandler": http.RedirectHandler,
		"Redirect":        http.Redirect,
		// "ArgServer":             http.ArgServer,
		// "DateServer":            http.DateServer,
		"PostForm":              http.PostForm,
		"ReadResponse":          http.ReadResponse,
		"NewRequestWithContext": http.NewRequestWithContext,
		"NewResponseController": http.NewResponseController,
		"ServeTLS":              http.ServeTLS,
		"NewServeMux":           http.NewServeMux,
		"ProxyFromEnvironment":  http.ProxyFromEnvironment,
		"Post":                  http.Post,
		"ServeContent":          http.ServeContent,
		"ReadRequest":           http.ReadRequest,
		"ParseHTTPVersion":      http.ParseHTTPVersion,
		"AllowQuerySemicolons":  http.AllowQuerySemicolons,
		"Handle":                http.Handle,
		"Serve":                 http.Serve,
		"DetectContentType":     http.DetectContentType,
		"Head":                  http.Head,
		"ServeFile":             http.ServeFile,
		"ProxyURL":              http.ProxyURL,
		// "Logger":                http.Logger,
		"FS":                 http.FS,
		"CanonicalHeaderKey": http.CanonicalHeaderKey,
		// constants
		"SameSiteDefaultMode":                 http.SameSiteDefaultMode,
		"SameSiteLaxMode":                     http.SameSiteLaxMode,
		"SameSiteStrictMode":                  http.SameSiteStrictMode,
		"SameSiteNoneMode":                    http.SameSiteNoneMode,
		"MethodGet":                           http.MethodGet,
		"MethodHead":                          http.MethodHead,
		"MethodPost":                          http.MethodPost,
		"MethodPut":                           http.MethodPut,
		"MethodPatch":                         http.MethodPatch,
		"MethodDelete":                        http.MethodDelete,
		"MethodConnect":                       http.MethodConnect,
		"MethodOptions":                       http.MethodOptions,
		"MethodTrace":                         http.MethodTrace,
		"TrailerPrefix":                       http.TrailerPrefix,
		"DefaultMaxHeaderBytes":               http.DefaultMaxHeaderBytes,
		"TimeFormat":                          http.TimeFormat,
		"StateNew":                            http.StateNew,
		"StateActive":                         http.StateActive,
		"StateIdle":                           http.StateIdle,
		"StateHijacked":                       http.StateHijacked,
		"StateClosed":                         http.StateClosed,
		"StatusContinue":                      http.StatusContinue,
		"StatusSwitchingProtocols":            http.StatusSwitchingProtocols,
		"StatusProcessing":                    http.StatusProcessing,
		"StatusEarlyHints":                    http.StatusEarlyHints,
		"StatusOK":                            http.StatusOK,
		"StatusCreated":                       http.StatusCreated,
		"StatusAccepted":                      http.StatusAccepted,
		"StatusNonAuthoritativeInfo":          http.StatusNonAuthoritativeInfo,
		"StatusNoContent":                     http.StatusNoContent,
		"StatusResetContent":                  http.StatusResetContent,
		"StatusPartialContent":                http.StatusPartialContent,
		"StatusMultiStatus":                   http.StatusMultiStatus,
		"StatusAlreadyReported":               http.StatusAlreadyReported,
		"StatusIMUsed":                        http.StatusIMUsed,
		"StatusMultipleChoices":               http.StatusMultipleChoices,
		"StatusMovedPermanently":              http.StatusMovedPermanently,
		"StatusFound":                         http.StatusFound,
		"StatusSeeOther":                      http.StatusSeeOther,
		"StatusNotModified":                   http.StatusNotModified,
		"StatusUseProxy":                      http.StatusUseProxy,
		"StatusTemporaryRedirect":             http.StatusTemporaryRedirect,
		"StatusPermanentRedirect":             http.StatusPermanentRedirect,
		"StatusBadRequest":                    http.StatusBadRequest,
		"StatusUnauthorized":                  http.StatusUnauthorized,
		"StatusPaymentRequired":               http.StatusPaymentRequired,
		"StatusForbidden":                     http.StatusForbidden,
		"StatusNotFound":                      http.StatusNotFound,
		"StatusMethodNotAllowed":              http.StatusMethodNotAllowed,
		"StatusNotAcceptable":                 http.StatusNotAcceptable,
		"StatusProxyAuthRequired":             http.StatusProxyAuthRequired,
		"StatusRequestTimeout":                http.StatusRequestTimeout,
		"StatusConflict":                      http.StatusConflict,
		"StatusGone":                          http.StatusGone,
		"StatusLengthRequired":                http.StatusLengthRequired,
		"StatusPreconditionFailed":            http.StatusPreconditionFailed,
		"StatusRequestEntityTooLarge":         http.StatusRequestEntityTooLarge,
		"StatusRequestURITooLong":             http.StatusRequestURITooLong,
		"StatusUnsupportedMediaType":          http.StatusUnsupportedMediaType,
		"StatusRequestedRangeNotSatisfiable":  http.StatusRequestedRangeNotSatisfiable,
		"StatusExpectationFailed":             http.StatusExpectationFailed,
		"StatusTeapot":                        http.StatusTeapot,
		"StatusMisdirectedRequest":            http.StatusMisdirectedRequest,
		"StatusUnprocessableEntity":           http.StatusUnprocessableEntity,
		"StatusLocked":                        http.StatusLocked,
		"StatusFailedDependency":              http.StatusFailedDependency,
		"StatusTooEarly":                      http.StatusTooEarly,
		"StatusUpgradeRequired":               http.StatusUpgradeRequired,
		"StatusPreconditionRequired":          http.StatusPreconditionRequired,
		"StatusTooManyRequests":               http.StatusTooManyRequests,
		"StatusRequestHeaderFieldsTooLarge":   http.StatusRequestHeaderFieldsTooLarge,
		"StatusUnavailableForLegalReasons":    http.StatusUnavailableForLegalReasons,
		"StatusInternalServerError":           http.StatusInternalServerError,
		"StatusNotImplemented":                http.StatusNotImplemented,
		"StatusBadGateway":                    http.StatusBadGateway,
		"StatusServiceUnavailable":            http.StatusServiceUnavailable,
		"StatusGatewayTimeout":                http.StatusGatewayTimeout,
		"StatusHTTPVersionNotSupported":       http.StatusHTTPVersionNotSupported,
		"StatusVariantAlsoNegotiates":         http.StatusVariantAlsoNegotiates,
		"StatusInsufficientStorage":           http.StatusInsufficientStorage,
		"StatusLoopDetected":                  http.StatusLoopDetected,
		"StatusNotExtended":                   http.StatusNotExtended,
		"StatusNetworkAuthenticationRequired": http.StatusNetworkAuthenticationRequired,
		"DefaultMaxIdleConnsPerHost":          http.DefaultMaxIdleConnsPerHost,
		// variable
		"DefaultClient":           http.DefaultClient,
		"ErrUseLastResponse":      http.ErrUseLastResponse,
		"NoBody":                  http.NoBody,
		"ErrMissingFile":          http.ErrMissingFile,
		"ErrNotSupported":         http.ErrNotSupported,
		"ErrUnexpectedTrailer":    http.ErrUnexpectedTrailer,
		"ErrMissingBoundary":      http.ErrMissingBoundary,
		"ErrNotMultipart":         http.ErrNotMultipart,
		"ErrHeaderTooLong":        http.ErrHeaderTooLong,
		"ErrShortBody":            http.ErrShortBody,
		"ErrMissingContentLength": http.ErrMissingContentLength,
		"ErrNoCookie":             http.ErrNoCookie,
		"ErrNoLocation":           http.ErrNoLocation,
		"ErrBodyNotAllowed":       http.ErrBodyNotAllowed,
		"ErrHijacked":             http.ErrHijacked,
		"ErrContentLength":        http.ErrContentLength,
		"ErrWriteAfterFlush":      http.ErrWriteAfterFlush,
		"ServerContextKey":        http.ServerContextKey,
		"LocalAddrContextKey":     http.LocalAddrContextKey,
		"ErrAbortHandler":         http.ErrAbortHandler,
		"DefaultServeMux":         http.DefaultServeMux,
		"ErrServerClosed":         http.ErrServerClosed,
		"ErrHandlerTimeout":       http.ErrHandlerTimeout,
		"ErrLineTooLong":          http.ErrLineTooLong,
		"ErrBodyReadAfterClose":   http.ErrBodyReadAfterClose,
		"DefaultTransport":        http.DefaultTransport,
		"ErrSkipAltProtocol":      http.ErrSkipAltProtocol,
		"Client":                  netHttpClient,
	})
}

func netHttpClient() *http.Client {
	return &http.Client{}
}
