# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yock.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nyock.proto\x12\x04Yock\"\r\n\x0bPingRequest\"\x0e\n\x0cPingResponse\"&\n\x0b\x43\x61llRequest\x12\n\n\x02\x46n\x18\x01 \x01(\t\x12\x0b\n\x03\x41rg\x18\x02 \x01(\t\"\x1b\n\x0c\x43\x61llResponse\x12\x0b\n\x03\x42uf\x18\x01 \x01(\t\"\r\n\x0bInfoRequest\"\x0e\n\x0cInfoResponse2\x9c\x01\n\rYockInterface\x12-\n\x04Ping\x12\x11.Yock.PingRequest\x1a\x12.Yock.PingResponse\x12-\n\x04\x43\x61ll\x12\x11.Yock.CallRequest\x1a\x12.Yock.CallResponse\x12-\n\x04Info\x12\x11.Yock.InfoRequest\x1a\x12.Yock.InfoResponseB\x19\n\x05yockiZ\x08./;yocki\xaa\x02\x05yockib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yock_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\005yockiZ\010./;yocki\252\002\005yocki'
  _PINGREQUEST._serialized_start=20
  _PINGREQUEST._serialized_end=33
  _PINGRESPONSE._serialized_start=35
  _PINGRESPONSE._serialized_end=49
  _CALLREQUEST._serialized_start=51
  _CALLREQUEST._serialized_end=89
  _CALLRESPONSE._serialized_start=91
  _CALLRESPONSE._serialized_end=118
  _INFOREQUEST._serialized_start=120
  _INFOREQUEST._serialized_end=133
  _INFORESPONSE._serialized_start=135
  _INFORESPONSE._serialized_end=149
  _YOCKINTERFACE._serialized_start=152
  _YOCKINTERFACE._serialized_end=308
# @@protoc_insertion_point(module_scope)
