# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yocki.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0byocki.proto\x12\x05Yocki\"\r\n\x0bPingRequest\"\x0e\n\x0cPingResponse\"&\n\x0b\x43\x61llRequest\x12\n\n\x02\x46n\x18\x01 \x01(\t\x12\x0b\n\x03\x41rg\x18\x02 \x01(\t\"\x1b\n\x0c\x43\x61llResponse\x12\x0b\n\x03\x42uf\x18\x01 \x01(\t\"\r\n\x0bInfoRequest\"\x0e\n\x0cInfoResponse2\xa2\x01\n\rYockInterface\x12/\n\x04Ping\x12\x12.Yocki.PingRequest\x1a\x13.Yocki.PingResponse\x12/\n\x04\x43\x61ll\x12\x12.Yocki.CallRequest\x1a\x13.Yocki.CallResponse\x12/\n\x04Info\x12\x12.Yocki.InfoRequest\x1a\x13.Yocki.InfoResponseB\x19\n\x05protoZ\x08./;proto\xaa\x02\x05protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yocki_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'\n\005protoZ\010./;proto\252\002\005proto'
    _PINGREQUEST._serialized_start = 22
    _PINGREQUEST._serialized_end = 35
    _PINGRESPONSE._serialized_start = 37
    _PINGRESPONSE._serialized_end = 51
    _CALLREQUEST._serialized_start = 53
    _CALLREQUEST._serialized_end = 91
    _CALLRESPONSE._serialized_start = 93
    _CALLRESPONSE._serialized_end = 120
    _INFOREQUEST._serialized_start = 122
    _INFOREQUEST._serialized_end = 135
    _INFORESPONSE._serialized_start = 137
    _INFORESPONSE._serialized_end = 151
    _YOCKINTERFACE._serialized_start = 154
    _YOCKINTERFACE._serialized_end = 316
# @@protoc_insertion_point(module_scope)
